### PR TITLE
Add top navigation bar

### PR DESCRIPTION
**Pull request by congruiyS2023**
Add HeaderNav component, please use this component as top navigation bar.

## Params:
- `header`: header text
- `showBackButton`:  whether to show back arrow on the left
- `backButtonOnClick`: handler to handle `click` event on back button
- `showPlusButton`: whether to show plus button on the right
- `plusButtonOnClick`: handler to handle `click` event on plus button
- `showLogOutButton`: whether to show logout button on the right
image

### CODE REVIEW

**Comment by hanqidS2023** [comment]
In addition, I think this part can be considered as a template as well, since I see most our restaurant owner flow pages in the Figma is having both the bot nav and header nav, what do you think?

**Comment by congruiyS2023** [comment]
> In addition, I think this part can be considered as a template as well, since I see most our restaurant owner flow pages in the Figma is having both the bot nav and header nav, what do you think?

Yes, that's exactly what I mean. We should use this across the app. What do you think of the design of this compoenent?

**Comment by hanqidS2023** [comment]
> > In addition, I think this part can be considered as a template as well, since I see most our restaurant owner flow pages in the Figma is having both the bot nav and header nav, what do you think?
> 
> Yes, that's exactly what I mean. We should use this across the app. What do you think of the design of this compoenent?

I think it's good. In this case we might want to modify our Figma prototype

**Comment by congruiyS2023** [comment]
> > > In addition, I think this part can be considered as a template as well, since I see most our restaurant owner flow pages in the Figma is having both the bot nav and header nav, what do you think?
> > 
> > 
> > Yes, that's exactly what I mean. We should use this across the app. What do you think of the design of this compoenent?
> 
> I think it's good. In this case we might want to modify our Figma prototype

We can hold on for Figma change. I think we can finish the app with this header, and check with the teaching team on Monday if we actually need to change Figma design.

**Comment by ziyangcS2023** [comment]
ok

**Review by ziyangcS2023 — APPROVED** [review]

**Pull request merged**
