### PR TITLE
Modify Header Nav to support logout & home page done

### PR DESCRIPTION
**Pull request by hanqidS2023**
login url: /login/restaurant, /login/company, /login/customer
logout url: /logout/your_preivous_page_url(e.g. If you click logout in /reward/abc the logout page url would be: /logout/reward/abc)

### CODE REVIEW

**Comment by hanqidS2023** [comment]
For pages need Nav bar, please import NavBar component and add<Navbar /> in the render related code

**Comment by hanqidS2023** [comment]
Screenshot 2023-12-04 at 12 18 00 AM
Screenshot 2023-12-04 at 12 18 49 AM
Screenshot 2023-12-04 at 12 19 07 AM
Screenshot 2023-12-04 at 12 19 27 AM

**Comment by congruiyS2023** [comment]
Just thought of this: could you please clear the `localStorage` when user clicks on the logout button? I believe this can be done via add extra behavior to [the logout button](https://github.com/congruiyS2023/platemate-web/blob/814e2334a7b1a20321d7fa1ce9603bb8866d80af/src/components/HeaderNav.jsx#L37), as in add an on-click function to the button. The function should navigate to the login page as well as clear the `localStorage`. (You know what, now that I look at the `HeaderNav`, it looks a little dumb lol)

**Comment by hanqidS2023** [comment]
> Just thought of this: could you please clear the `localStorage` when user clicks on the logout button? I believe this can be done via add extra behavior to [the logout button](https://github.com/congruiyS2023/platemate-web/blob/814e2334a7b1a20321d7fa1ce9603bb8866d80af/src/components/HeaderNav.jsx#L37), as in add an on-click function to the button. The function should navigate to the login page as well as clear the `localStorage`. (You know what, now that I look at the `HeaderNav`, it looks a little dumb lol)

Good suggestion. Now when user confirm logging out(click on 'yes') in the log out page, the localStorage will be cleared

**Review by congruiyS2023 — APPROVED** [review]
LGTM! Great work!

**Pull request merged**
